### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined

### ISSUE THREAD

**Issue by Supertigerr** [yue/yackage#20]
Whenever i require "discord.js" npm package, i get this error when opening the exe file: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined
    at Function.alloc (node:buffer:372:3)
    at AsarArchive.readFile (asar_archive.js:99:27)
    at fs.readFileSync (asar_monkey_patch.js:379:40)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node: internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\project\out\project.exe\asar\node_modules\lodash\_castPath.js:1:109)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
```
Any ideas?

**Comment by Supertigerr** [comment]
From my very hard troubleshooting, it seems like `const EventEmitter = require('node:events');` is causing this issue.
