### ISSUE TITLE
Error at install module

### ISSUE THREAD

**Issue by sen0rxol0** [yue/yackage#21]
node -v: 16.16.0

[1/2] ⠐ fetch-yode
error /*/*/*/*/*/node_modules/fetch-yode: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /*/*/*/*/node_modules/fetch-yode
Output:
Failed to install Yode ReferenceError: fetch is not defined
    at getYodeVersionFromPrefix (/*/*/*/*/node_modules/fetch-yode/lib/versions.js:29:17)
    at getYodeVersionFromNode (/*/*/*/*/node_modules/fetch-yode/lib/versions.js:22:16)
    at main (/*/*/*/*/node_modules/fetch-yode/lib/install.js:16:29)
    at Object.<anonymous> (/*/*/*/*/node_modules/fetch-yode/lib/install.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by zcbenz** [comment]
`fetch-yode` requires Node >= 18 for the builtin `fetch` support.
