### ISSUE TITLE
built app is turned off as soon as it is turned on in macOS.

### ISSUE THREAD

**Issue by disjukr** [yue/yackage#5]
i just executed `yackage dist out`.
same problem reproduced in the [yue-sample-apps](https://github.com/yue/yue-sample-apps) project.

macOS version: High Sierra 10.13.4 (17E202)

```sh
$ node --version
v8.11.1

$ yackage --version
v0.2.5

$ ls yode
yode-latest-release    yode-v0.3.4-darwin-x64

$ cat yode/yode-latest-release
{"tag_name":"v0.3.4","time":1525398023311}

$ ./out/myapp.app/Contents/MacOS/myapp
buffer.js:224
    throw err;
    ^

TypeError: "size" argument must be a number
    at Function.Buffer.alloc (buffer.js:233:3)
    at AsarArchive.readFile (asar_archive.js:96:27)
    at AsarArchive.copyFileOut (asar_archive.js:114:36)
    at Object.module.(anonymous function) [as .node] (asar_monkey_patch.js:114:41)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/myapp/out/myapp.app/Contents/MacOS/myapp/asar/node_modules/gui/index.js:1:190)
```

**Comment by zcbenz** [comment]
Fixed with https://github.com/yue/yode/commit/3e0ac9a1f3d6ded4dd334fa1637328cdb8f41274.

**Comment by disjukr** [comment]
great. thanks!

**Comment by Supertigerr** [comment]
I'm getting a similar error, any ideas?
```
TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received undefined
    at Function.alloc (node:buffer:372:3)
    at AsarArchive.readFile (asar_archive.js:99:27)
    at fs.readFileSync (asar_monkey_patch.js:379:40)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\Coding\NodeJS Projects\discord-spotify-v2\music-discord-rpc\ignore\out\spotify-local-socket.exe\asar\node_modules\lodash\_castPath.js:1:109)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    ```
