### ISSUE TITLE
Build error: path must be a string or Buffer

### ISSUE THREAD

**Issue by eveningkid** [yue/yackage#6]
Hi @zcbenz, 

Thanks a lot for working on this project, it makes me happy to see such an advanced open-sourced project. Thank you very much for all your hard work.

> TypeError: path must be a string or Buffer

I ran into the following issue as I was trying to build a sample app (from the _getting started_ text editor  example). I used the [install.js node script](https://github.com/yue/wey/blob/master/scripts/install.js) from the wey app.

[In case you need the code I have for my `index.js` file.](https://gist.github.com/eveningkid/aa0d6ffc942413b63f44a103ee831be7)

```
$ node --version
v9.0.0

$ yackage --version
v0.2.5

$ ls yode
yode-v0.3.4-darwin-x64

$ npm run build          

> get-started@1.0.0 build /Users/arnaud/Documents/projects/yue/get-started
> yackage build out --cache-dir yode --unpack "+(*.node|*.html|*.png)"

TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:375:11)
    at go$readFile (/usr/local/lib/node_modules/yackage/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/usr/local/lib/node_modules/yackage/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Promise (/usr/local/lib/node_modules/yackage/node_modules/universalify/index.js:13:12)
    at new Promise (<anonymous>)
    at Object.readFile (/usr/local/lib/node_modules/yackage/node_modules/universalify/index.js:7:14)
    at writeLicenseFile (/usr/local/lib/node_modules/yackage/lib/main.js:191:30)
    at <anonymous>
```

Thank you for your time!

**Comment by zcbenz** [comment]
Using yackage@0.2.6 should be able to fix this.

**Comment by eveningkid** [comment]
Thank you, works perfectly now!
