### ISSUE TITLE
Error when packaging

### ISSUE THREAD

**Issue by computerquip-streamlabs** [yue/yackage#7]
I get this error when packaging with this command: `yarn run yackage build build --app-dir .`
I've modified the paths to not show my working directory.
```
Error: No packages found in this path..
    at <snip>\node_modules\license-checker\lib\index.js:396:19
    at <snip>\node_modules\read-installed\read-installed.js:142:5
    at next (<snip>\node_modules\read-installed\read-installed.js:189:14)
    at <snip>\node_modules\read-installed\read-installed.js:173:14
    at <snip>\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by computerquip-streamlabs** [comment]
I figured out the issue. `npm pack` was failing internally. So when freshDir was passed to license-checker, nothing was in it. This was caused by my version string being 1.0 instead of 1.0.0 on accident. Closing but I'd probably suggest checking the output of those commands.
